# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/royalstate/Projects and Research/Python Projects/Globetrack-Monitoring/Newspaper/utils/main_design_ui.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.page)
        self.frame.setStyleSheet("font: 10pt \"Alef\";")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMinimumSize(QtCore.QSize(100, 31))
        self.label.setMaximumSize(QtCore.QSize(115, 31))
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.paper_dir_edit = QtWidgets.QLineEdit(self.frame)
        self.paper_dir_edit.setMinimumSize(QtCore.QSize(0, 31))
        self.paper_dir_edit.setMaximumSize(QtCore.QSize(16777215, 31))
        self.paper_dir_edit.setReadOnly(True)
        self.paper_dir_edit.setObjectName("paper_dir_edit")
        self.horizontalLayout_2.addWidget(self.paper_dir_edit)
        self.paper_dir_search_button = QtWidgets.QPushButton(self.frame)
        self.paper_dir_search_button.setMinimumSize(QtCore.QSize(75, 31))
        self.paper_dir_search_button.setMaximumSize(QtCore.QSize(80, 31))
        self.paper_dir_search_button.setObjectName("paper_dir_search_button")
        self.horizontalLayout_2.addWidget(self.paper_dir_search_button)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setMinimumSize(QtCore.QSize(100, 31))
        self.label_2.setMaximumSize(QtCore.QSize(115, 31))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.output_file_edit = QtWidgets.QLineEdit(self.frame)
        self.output_file_edit.setMinimumSize(QtCore.QSize(0, 31))
        self.output_file_edit.setMaximumSize(QtCore.QSize(16777215, 31))
        self.output_file_edit.setObjectName("output_file_edit")
        self.horizontalLayout_3.addWidget(self.output_file_edit)
        self.output_file_search_button = QtWidgets.QPushButton(self.frame)
        self.output_file_search_button.setMinimumSize(QtCore.QSize(75, 31))
        self.output_file_search_button.setMaximumSize(QtCore.QSize(80, 31))
        self.output_file_search_button.setObjectName("output_file_search_button")
        self.horizontalLayout_3.addWidget(self.output_file_search_button)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.add_mail_to_listing_button = QtWidgets.QPushButton(self.groupBox)
        self.add_mail_to_listing_button.setMinimumSize(QtCore.QSize(23, 31))
        self.add_mail_to_listing_button.setMaximumSize(QtCore.QSize(23, 31))
        self.add_mail_to_listing_button.setObjectName("add_mail_to_listing_button")
        self.horizontalLayout_4.addWidget(self.add_mail_to_listing_button)
        self.delete_mail_from_listing_button = QtWidgets.QPushButton(self.groupBox)
        self.delete_mail_from_listing_button.setMinimumSize(QtCore.QSize(23, 31))
        self.delete_mail_from_listing_button.setMaximumSize(QtCore.QSize(23, 31))
        self.delete_mail_from_listing_button.setObjectName("delete_mail_from_listing_button")
        self.horizontalLayout_4.addWidget(self.delete_mail_from_listing_button)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setMinimumSize(QtCore.QSize(240, 31))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 31))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.mail_list_listwidget = QtWidgets.QListWidget(self.groupBox)
        self.mail_list_listwidget.setMinimumSize(QtCore.QSize(240, 0))
        self.mail_list_listwidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.mail_list_listwidget.setAlternatingRowColors(True)
        self.mail_list_listwidget.setObjectName("mail_list_listwidget")
        self.verticalLayout_2.addWidget(self.mail_list_listwidget)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(9)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.move_mails_into_send_list_button = QtWidgets.QPushButton(self.groupBox)
        self.move_mails_into_send_list_button.setMinimumSize(QtCore.QSize(75, 31))
        self.move_mails_into_send_list_button.setMaximumSize(QtCore.QSize(75, 31))
        self.move_mails_into_send_list_button.setObjectName("move_mails_into_send_list_button")
        self.verticalLayout_4.addWidget(self.move_mails_into_send_list_button)
        self.move_mails_from_send_list_button = QtWidgets.QPushButton(self.groupBox)
        self.move_mails_from_send_list_button.setMinimumSize(QtCore.QSize(75, 31))
        self.move_mails_from_send_list_button.setMaximumSize(QtCore.QSize(75, 31))
        self.move_mails_from_send_list_button.setObjectName("move_mails_from_send_list_button")
        self.verticalLayout_4.addWidget(self.move_mails_from_send_list_button)
        self.clear_send_list_button = QtWidgets.QPushButton(self.groupBox)
        self.clear_send_list_button.setMinimumSize(QtCore.QSize(75, 31))
        self.clear_send_list_button.setMaximumSize(QtCore.QSize(75, 31))
        self.clear_send_list_button.setObjectName("clear_send_list_button")
        self.verticalLayout_4.addWidget(self.clear_send_list_button)
        self.start_ops_button = QtWidgets.QPushButton(self.groupBox)
        self.start_ops_button.setMinimumSize(QtCore.QSize(75, 31))
        self.start_ops_button.setMaximumSize(QtCore.QSize(75, 31))
        self.start_ops_button.setObjectName("start_ops_button")
        self.verticalLayout_4.addWidget(self.start_ops_button)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setMinimumSize(QtCore.QSize(300, 31))
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 31))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.teo_send_listwidget = QtWidgets.QListWidget(self.groupBox)
        self.teo_send_listwidget.setMinimumSize(QtCore.QSize(300, 0))
        self.teo_send_listwidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.teo_send_listwidget.setAlternatingRowColors(True)
        self.teo_send_listwidget.setObjectName("teo_send_listwidget")
        self.verticalLayout_3.addWidget(self.teo_send_listwidget)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_6.addWidget(self.groupBox)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.output_log_textedit = QtWidgets.QTextEdit(self.frame_2)
        self.output_log_textedit.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.output_log_textedit.setObjectName("output_log_textedit")
        self.verticalLayout_5.addWidget(self.output_log_textedit)
        self.verticalLayout_6.addWidget(self.frame_2)
        self.groupBox.raise_()
        self.paper_dir_search_button.raise_()
        self.paper_dir_edit.raise_()
        self.label.raise_()
        self.frame_2.raise_()
        self.verticalLayout.addWidget(self.frame)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.horizontalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Paper Directory :"))
        self.paper_dir_search_button.setText(_translate("MainWindow", "Search"))
        self.label_2.setText(_translate("MainWindow", "Output File :"))
        self.output_file_search_button.setText(_translate("MainWindow", "Search"))
        self.groupBox.setTitle(_translate("MainWindow", "Mail Listing"))
        self.add_mail_to_listing_button.setText(_translate("MainWindow", "+"))
        self.delete_mail_from_listing_button.setText(_translate("MainWindow", "-"))
        self.label_3.setText(_translate("MainWindow", "Mail List"))
        self.move_mails_into_send_list_button.setText(_translate("MainWindow", ">"))
        self.move_mails_from_send_list_button.setText(_translate("MainWindow", "<"))
        self.clear_send_list_button.setText(_translate("MainWindow", "Clear"))
        self.start_ops_button.setText(_translate("MainWindow", "Start"))
        self.label_4.setText(_translate("MainWindow", "To Send"))
