[postgres]
host = "localhost"
port = 5432
dbname = "haron test base"
user = "postgres"
password = "hellenaoko168"


#[postgres]
#host = "151.80.209.133"
#port = 5432
#dbname = "Haron CRM Software"
#user = "postgres"
#password = "calm@2020"